name: Packaging
on: pull_request

jobs:
  release-tarball:
    runs-on: ubuntu-latest
    name: Build release tarball
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: Set up php$
        uses: shivammathur/setup-php@c5fc0d8281aba02c7fda07d3a70cc5371548067d
        with:
          php-version: 8.0
          tools: composer
          extensions: ctype,curl,dom,gd,iconv,intl,json,mbstring,openssl,posix,sqlite,xml,zip,gmp
          coverage: none
      - name: Install Krankerl
        run: |
          wget https://github.com/ChristophWurst/krankerl/releases/download/v0.14.0/krankerl_0.14.0_amd64.deb
          sudo dpkg -i krankerl_0.14.0_amd64.deb
      - name: Package app
        run: krankerl package
      - uses: actions/upload-artifact@v3
        with:
          path: build/artifacts/calendar.tar.gz
          if-no-files-found: error
